package com.zzp.hhtally.network.textin

object TextInValue {
    val kindMap = {
        "traffic" to "交通"
        "office" to "办公"
        "daily" to "日用"
        "service" to "服务"
        "digital_appliance" to "数码电器"
        "rent_decoration" to "房租装饰"
        "communication" to "通讯"
        "lodging" to "住宿"
        "post" to "邮寄"
        "medical_treatment" to "医疗"
        "repast" to "餐饮"
        "foodstuff" to "食品"
        "raiment" to "服饰"
        "service" to "服务"
        "vehicle" to "用车"
        "education" to "教育"
        "other" to "其他"
    }

    val typeMap = {
        "air_transport" to "行程单"
        "blockchain_electronic_invoice" to "区块链电子发票"
        "education_receipt" to "教育费收据"
        "general_machine_invoice" to "通用机打发票"
        "highway_passenger_invoice" to "公路客运发票"
        "machine_printed_invoice" to "机打发票"
        "medical_receipt" to "医疗费收据"
        "motor_vehicle_sale_invoice" to "机动车销售统一发票"
        "non_tax_income_unified_bill" to "非税收入票据"
        "parking_invoice" to "停车费发票"
        "passenger_transport_invoice" to "旅客运输普票"
        "quota_invoice" to "通用定额发票"
        "shipping_invoice" to "船运客票"
        "shop_receipt" to "商户小票"
        "taxi_ticket" to "出租车发票"
        "train_ticket" to "火车票"
        "travel_transport" to "出行行程单"
        "used_car_purchase_invoice" to "二手车销售统一发票"
        "vat_common_invoice" to "增值税普通发票"
        "vat_electronic_invoice" to "增值税电子普通发票"
        "vat_electronic_special_invoice" to "增值税电子专用发票"
        "vat_electronic_toll_invoice" to "增值税电子普通发票(通行费)"
        "vat_electronic_invoice_new" to "电子发票(普通发票)"
        "vat_electronic_special_invoice_new" to "电子发票(增值税专用发票)"
        "vat_invoice_sales_list" to "增值税销货清单"
        "vat_roll_invoice" to "增值税普通发票(卷票)"
        "vat_special_invoice" to "增值税专用发票"
        "vat_transport_invoice" to "货物运输业增值税专用发票"
        "vehicle_toll" to "过路过桥费发票"
        "other" to "其他"
    }
}
